export const genres = [
  "18th century",
  "19th century",
  "20th century",
  "absurdist",
  "adventure",
  "american",
  "biography",
  "black",
  "british",
  "children",
  "class",
  "classics",
  "coming of age",
  "conflict",
  "crime",
  "dystopian", 
  "economics",
  "fantasy",
  "fate",
  "feminism",
  "fiction",
  "french",
  "german",
  "gothic",
  "greek",
  "greek mythology",
  "historical fiction",
  "history",
  "horror",
  "humor",
  "irish",
  "literature",
  "love",
  "magic",
  "marriage",
  "mental health",
  "mystery",
  "nature",
  "non-fiction",
  "philosophy",
  "poetry",
  "political science",
  "politics",
  "psychological thriller",
  "psychology",
  "regency",
  "religion",
  "romance",
  "russian",
  "satire",
  "science fiction",
  "short stories",
  "slavery",
  "sociology",
  "spanish",
  "theatre",
  "theory",
  "thriller",
  "tragedy",
  "travel",
  "vampire",
  "victorian",
  "war",
  "young adult"
]